language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: surge
  skip_cleanup: true
  domain: some-trial-app.surge.sh
  project: ./build/
on:
  branch: master